import type { Metadata } from "next";
import { Bree_Serif, Chau_Philomene_One } from "next/font/google";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const breeSerif = Bree_Serif({
  variable: "--font-bree-serif",
  subsets: ["latin"],
  weight: ["400"],
});

const chauPhilomeneOne = Chau_Philomene_One({
  variable: "--font-chau-philomene-one",
  subsets: ["latin"],
  weight: ["400"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${breeSerif.variable} ${chauPhilomeneOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
